//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogin
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public string ApplicationCode { get; set; }
        public string IpAddress { get; set; }
        public string Hostname { get; set; }
        public System.DateTime LogIn { get; set; }
        public Nullable<System.DateTime> LogOut { get; set; }
        public Nullable<bool> Repair { get; set; }
        public Nullable<System.DateTime> SystemDatetime { get; set; }
    
        public virtual Usr Usr { get; set; }
    }
}
