//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bidding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bidding()
        {
            this.Bidding1 = new HashSet<Bidding>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public int IdOffer { get; set; }
        public Nullable<int> IdParentBidding { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<bool> IsFinal { get; set; }
        public Nullable<int> SmjerBiddingReply { get; set; }
        public Nullable<int> IdBuyerComany { get; set; }
        public Nullable<int> IdUser { get; set; }
        public int IdCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> IdUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bidding> Bidding1 { get; set; }
        public virtual Bidding Bidding2 { get; set; }
        public virtual Company Company { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual Usr Usr { get; set; }
    }
}
