//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirFish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DirFish()
        {
            this.OfferItem = new HashSet<OfferItem>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public Nullable<int> IdFishType { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public int IdCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> IdUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual DirFishType DirFishType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferItem> OfferItem { get; set; }
    }
}
