//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.OfferItem = new HashSet<OfferItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCompany { get; set; }
        public Nullable<int> IdShip { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> IdReturnPort { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public Nullable<System.DateTime> HandoverTimeInPort { get; set; }
        public string HandoverLocationOutPort { get; set; }
        public Nullable<System.DateTime> HandoverTimeOutPort { get; set; }
        public Nullable<System.DateTime> ValidTime { get; set; }
        public Nullable<int> IdPaymentMethod { get; set; }
        public int IdUser { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Active { get; set; }
        public int IdCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> IdUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual DirPaymentMethod DirPaymentMethod { get; set; }
        public virtual Port Port { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual Usr Usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferItem> OfferItem { get; set; }
    }
}
