//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ship()
        {
            this.Offer = new HashSet<Offer>();
        }
    
        public int Id { get; set; }
        public string ShipName { get; set; }
        public string ShipRegistration { get; set; }
        public Nullable<double> LengthFloat { get; set; }
        public Nullable<float> LengthReal { get; set; }
        public Nullable<int> IdShipType { get; set; }
        public Nullable<float> Capacity { get; set; }
        public Nullable<int> IdCompany { get; set; }
        public Nullable<int> IdCaptain { get; set; }
        public Nullable<int> IdBasePort { get; set; }
        public Nullable<int> IdUnloadPort { get; set; }
        public Nullable<bool> Active { get; set; }
        public int IdCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> IdUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual DirShipType DirShipType { get; set; }
        public virtual Port Port { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual Prs Prs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offer { get; set; }
    }
}
