using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:57:14
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="DirFishingZone"/> and <see cref="DirFishingZoneDto"/>.
    /// </summary>
    public static partial class DirFishingZoneHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DirFishingZoneDto"/> converted from <see cref="DirFishingZone"/>.</param>
        static partial void OnDTO(this DirFishingZone entity, DirFishingZoneDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DirFishingZone"/> converted from <see cref="DirFishingZoneDto"/>.</param>
        static partial void OnEntity(this DirFishingZoneDto dto, DirFishingZone entity);

        /// <summary>
        /// Converts this instance of <see cref="DirFishingZoneDto"/> to an instance of <see cref="DirFishingZone"/>.
        /// </summary>
        /// <param name="dto"><see cref="DirFishingZoneDto"/> to convert.</param>
        public static DirFishingZone ToEntity(this DirFishingZoneDto dto)
        {
            if (dto == null) return null;

            var entity = new DirFishingZone();

            entity.Id = dto.Id;
            entity.Code = dto.Code;
            entity.Name = dto.Name;
            entity.Text = dto.Text;
            entity.Rank = dto.Rank;
            entity.Description = dto.Description;
            entity.Active = dto.Active;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DirFishingZone"/> to an instance of <see cref="DirFishingZoneDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="DirFishingZone"/> to convert.</param>
        public static DirFishingZoneDto ToDTO(this DirFishingZone entity)
        {
            if (entity == null) return null;

            var dto = new DirFishingZoneDto();

            dto.Id = entity.Id;
            dto.Code = entity.Code;
            dto.Name = entity.Name;
            dto.Text = entity.Text;
            dto.Rank = entity.Rank;
            dto.Description = entity.Description;
            dto.Active = entity.Active;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DirFishingZoneDto"/> to an instance of <see cref="DirFishingZone"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DirFishingZone> ToEntities(this IEnumerable<DirFishingZoneDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DirFishingZone"/> to an instance of <see cref="DirFishingZoneDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DirFishingZoneDto> ToDTOs(this IEnumerable<DirFishingZone> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}