using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:57:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="DirFishCategory"/> and <see cref="DirFishCategoryDto"/>.
    /// </summary>
    public static partial class DirFishCategoryHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DirFishCategoryDto"/> converted from <see cref="DirFishCategory"/>.</param>
        static partial void OnDTO(this DirFishCategory entity, DirFishCategoryDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DirFishCategory"/> converted from <see cref="DirFishCategoryDto"/>.</param>
        static partial void OnEntity(this DirFishCategoryDto dto, DirFishCategory entity);

        /// <summary>
        /// Converts this instance of <see cref="DirFishCategoryDto"/> to an instance of <see cref="DirFishCategory"/>.
        /// </summary>
        /// <param name="dto"><see cref="DirFishCategoryDto"/> to convert.</param>
        public static DirFishCategory ToEntity(this DirFishCategoryDto dto)
        {
            if (dto == null) return null;

            var entity = new DirFishCategory();

            entity.Id = dto.Id;
            entity.Code = dto.Code;
            entity.Name = dto.Name;
            entity.Text = dto.Text;
            entity.Description = dto.Description;
            entity.Active = dto.Active;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DirFishCategory"/> to an instance of <see cref="DirFishCategoryDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="DirFishCategory"/> to convert.</param>
        public static DirFishCategoryDto ToDTO(this DirFishCategory entity)
        {
            if (entity == null) return null;

            var dto = new DirFishCategoryDto();

            dto.Id = entity.Id;
            dto.Code = entity.Code;
            dto.Name = entity.Name;
            dto.Text = entity.Text;
            dto.Description = entity.Description;
            dto.Active = entity.Active;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DirFishCategoryDto"/> to an instance of <see cref="DirFishCategory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DirFishCategory> ToEntities(this IEnumerable<DirFishCategoryDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DirFishCategory"/> to an instance of <see cref="DirFishCategoryDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DirFishCategoryDto> ToDTOs(this IEnumerable<DirFishCategory> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}