using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:56:52
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="DirFish"/> and <see cref="DirFishDto"/>.
    /// </summary>
    public static partial class DirFishHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DirFishDto"/> converted from <see cref="DirFish"/>.</param>
        static partial void OnDTO(this DirFish entity, DirFishDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DirFish"/> converted from <see cref="DirFishDto"/>.</param>
        static partial void OnEntity(this DirFishDto dto, DirFish entity);

        /// <summary>
        /// Converts this instance of <see cref="DirFishDto"/> to an instance of <see cref="DirFish"/>.
        /// </summary>
        /// <param name="dto"><see cref="DirFishDto"/> to convert.</param>
        public static DirFish ToEntity(this DirFishDto dto)
        {
            if (dto == null) return null;

            var entity = new DirFish();

            entity.Id = dto.Id;
            entity.Code = dto.Code;
            entity.Name = dto.Name;
            entity.Text = dto.Text;
            entity.IdFishType = dto.IdFishType;
            entity.Description = dto.Description;
            entity.Active = dto.Active;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DirFish"/> to an instance of <see cref="DirFishDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="DirFish"/> to convert.</param>
        public static DirFishDto ToDTO(this DirFish entity)
        {
            if (entity == null) return null;

            var dto = new DirFishDto();

            dto.Id = entity.Id;
            dto.Code = entity.Code;
            dto.Name = entity.Name;
            dto.Text = entity.Text;
            dto.IdFishType = entity.IdFishType;
            dto.Description = entity.Description;
            dto.Active = entity.Active;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DirFishDto"/> to an instance of <see cref="DirFish"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DirFish> ToEntities(this IEnumerable<DirFishDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DirFish"/> to an instance of <see cref="DirFishDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DirFishDto> ToDTOs(this IEnumerable<DirFish> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}