using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:57:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="DirPortType"/> and <see cref="DirPortTypeDto"/>.
    /// </summary>
    public static partial class DirPortTypeHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DirPortTypeDto"/> converted from <see cref="DirPortType"/>.</param>
        static partial void OnDTO(this DirPortType entity, DirPortTypeDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DirPortType"/> converted from <see cref="DirPortTypeDto"/>.</param>
        static partial void OnEntity(this DirPortTypeDto dto, DirPortType entity);

        /// <summary>
        /// Converts this instance of <see cref="DirPortTypeDto"/> to an instance of <see cref="DirPortType"/>.
        /// </summary>
        /// <param name="dto"><see cref="DirPortTypeDto"/> to convert.</param>
        public static DirPortType ToEntity(this DirPortTypeDto dto)
        {
            if (dto == null) return null;

            var entity = new DirPortType();

            entity.Id = dto.Id;
            entity.Code = dto.Code;
            entity.Name = dto.Name;
            entity.Text = dto.Text;
            entity.Description = dto.Description;
            entity.Active = dto.Active;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DirPortType"/> to an instance of <see cref="DirPortTypeDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="DirPortType"/> to convert.</param>
        public static DirPortTypeDto ToDTO(this DirPortType entity)
        {
            if (entity == null) return null;

            var dto = new DirPortTypeDto();

            dto.Id = entity.Id;
            dto.Code = entity.Code;
            dto.Name = entity.Name;
            dto.Text = entity.Text;
            dto.Description = entity.Description;
            dto.Active = entity.Active;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DirPortTypeDto"/> to an instance of <see cref="DirPortType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DirPortType> ToEntities(this IEnumerable<DirPortTypeDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DirPortType"/> to an instance of <see cref="DirPortTypeDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DirPortTypeDto> ToDTOs(this IEnumerable<DirPortType> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}