using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:57:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="DirPaymentMethod"/> and <see cref="DirPaymentMethodDto"/>.
    /// </summary>
    public static partial class DirPaymentMethodHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DirPaymentMethodDto"/> converted from <see cref="DirPaymentMethod"/>.</param>
        static partial void OnDTO(this DirPaymentMethod entity, DirPaymentMethodDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DirPaymentMethod"/> converted from <see cref="DirPaymentMethodDto"/>.</param>
        static partial void OnEntity(this DirPaymentMethodDto dto, DirPaymentMethod entity);

        /// <summary>
        /// Converts this instance of <see cref="DirPaymentMethodDto"/> to an instance of <see cref="DirPaymentMethod"/>.
        /// </summary>
        /// <param name="dto"><see cref="DirPaymentMethodDto"/> to convert.</param>
        public static DirPaymentMethod ToEntity(this DirPaymentMethodDto dto)
        {
            if (dto == null) return null;

            var entity = new DirPaymentMethod();

            entity.Id = dto.Id;
            entity.Code = dto.Code;
            entity.Name = dto.Name;
            entity.Text = dto.Text;
            entity.Description = dto.Description;
            entity.Active = dto.Active;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DirPaymentMethod"/> to an instance of <see cref="DirPaymentMethodDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="DirPaymentMethod"/> to convert.</param>
        public static DirPaymentMethodDto ToDTO(this DirPaymentMethod entity)
        {
            if (entity == null) return null;

            var dto = new DirPaymentMethodDto();

            dto.Id = entity.Id;
            dto.Code = entity.Code;
            dto.Name = entity.Name;
            dto.Text = entity.Text;
            dto.Description = entity.Description;
            dto.Active = entity.Active;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DirPaymentMethodDto"/> to an instance of <see cref="DirPaymentMethod"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DirPaymentMethod> ToEntities(this IEnumerable<DirPaymentMethodDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DirPaymentMethod"/> to an instance of <see cref="DirPaymentMethodDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DirPaymentMethodDto> ToDTOs(this IEnumerable<DirPaymentMethod> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}