using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:57:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="DirShipType"/> and <see cref="DirShipTypeDto"/>.
    /// </summary>
    public static partial class DirShipTypeHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DirShipTypeDto"/> converted from <see cref="DirShipType"/>.</param>
        static partial void OnDTO(this DirShipType entity, DirShipTypeDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DirShipType"/> converted from <see cref="DirShipTypeDto"/>.</param>
        static partial void OnEntity(this DirShipTypeDto dto, DirShipType entity);

        /// <summary>
        /// Converts this instance of <see cref="DirShipTypeDto"/> to an instance of <see cref="DirShipType"/>.
        /// </summary>
        /// <param name="dto"><see cref="DirShipTypeDto"/> to convert.</param>
        public static DirShipType ToEntity(this DirShipTypeDto dto)
        {
            if (dto == null) return null;

            var entity = new DirShipType();

            entity.Id = dto.Id;
            entity.Code = dto.Code;
            entity.Name = dto.Name;
            entity.Text = dto.Text;
            entity.Description = dto.Description;
            entity.Active = dto.Active;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DirShipType"/> to an instance of <see cref="DirShipTypeDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="DirShipType"/> to convert.</param>
        public static DirShipTypeDto ToDTO(this DirShipType entity)
        {
            if (entity == null) return null;

            var dto = new DirShipTypeDto();

            dto.Id = entity.Id;
            dto.Code = entity.Code;
            dto.Name = entity.Name;
            dto.Text = entity.Text;
            dto.Description = entity.Description;
            dto.Active = entity.Active;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DirShipTypeDto"/> to an instance of <see cref="DirShipType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DirShipType> ToEntities(this IEnumerable<DirShipTypeDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DirShipType"/> to an instance of <see cref="DirShipTypeDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DirShipTypeDto> ToDTOs(this IEnumerable<DirShipType> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}