using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:58:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="Port"/> and <see cref="PortDto"/>.
    /// </summary>
    public static partial class PortHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="PortDto"/> converted from <see cref="Port"/>.</param>
        static partial void OnDTO(this Port entity, PortDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Port"/> converted from <see cref="PortDto"/>.</param>
        static partial void OnEntity(this PortDto dto, Port entity);

        /// <summary>
        /// Converts this instance of <see cref="PortDto"/> to an instance of <see cref="Port"/>.
        /// </summary>
        /// <param name="dto"><see cref="PortDto"/> to convert.</param>
        public static Port ToEntity(this PortDto dto)
        {
            if (dto == null) return null;

            var entity = new Port();

            entity.Id = dto.Id;
            entity.Code = dto.Code;
            entity.Name = dto.Name;
            entity.Text = dto.Text;
            entity.Description = dto.Description;
            entity.Active = dto.Active;
            entity.IdRegion = dto.IdRegion;
            entity.IdPortType = dto.IdPortType;
            entity.FishUnload = dto.FishUnload;
            entity.Country = dto.Country;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Port"/> to an instance of <see cref="PortDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="Port"/> to convert.</param>
        public static PortDto ToDTO(this Port entity)
        {
            if (entity == null) return null;

            var dto = new PortDto();

            dto.Id = entity.Id;
            dto.Code = entity.Code;
            dto.Name = entity.Name;
            dto.Text = entity.Text;
            dto.Description = entity.Description;
            dto.Active = entity.Active;
            dto.IdRegion = entity.IdRegion;
            dto.IdPortType = entity.IdPortType;
            dto.FishUnload = entity.FishUnload;
            dto.Country = entity.Country;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="PortDto"/> to an instance of <see cref="Port"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Port> ToEntities(this IEnumerable<PortDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Port"/> to an instance of <see cref="PortDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<PortDto> ToDTOs(this IEnumerable<Port> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}