using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:59:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="Region"/> and <see cref="RegionDto"/>.
    /// </summary>
    public static partial class RegionHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="RegionDto"/> converted from <see cref="Region"/>.</param>
        static partial void OnDTO(this Region entity, RegionDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Region"/> converted from <see cref="RegionDto"/>.</param>
        static partial void OnEntity(this RegionDto dto, Region entity);

        /// <summary>
        /// Converts this instance of <see cref="RegionDto"/> to an instance of <see cref="Region"/>.
        /// </summary>
        /// <param name="dto"><see cref="RegionDto"/> to convert.</param>
        public static Region ToEntity(this RegionDto dto)
        {
            if (dto == null) return null;

            var entity = new Region();

            entity.Id = dto.Id;
            entity.Code = dto.Code;
            entity.Name = dto.Name;
            entity.Text = dto.Text;
            entity.Active = dto.Active;
            entity.Description = dto.Description;
            entity.County = dto.County;
            entity.Country = dto.Country;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Region"/> to an instance of <see cref="RegionDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="Region"/> to convert.</param>
        public static RegionDto ToDTO(this Region entity)
        {
            if (entity == null) return null;

            var dto = new RegionDto();

            dto.Id = entity.Id;
            dto.Code = entity.Code;
            dto.Name = entity.Name;
            dto.Text = entity.Text;
            dto.Active = entity.Active;
            dto.Description = entity.Description;
            dto.County = entity.County;
            dto.Country = entity.Country;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="RegionDto"/> to an instance of <see cref="Region"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Region> ToEntities(this IEnumerable<RegionDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Region"/> to an instance of <see cref="RegionDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<RegionDto> ToDTOs(this IEnumerable<Region> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}