using EF;
using System.Linq;
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:59:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{

    /// <summary>
    /// Assembler for <see cref="Usr"/> and <see cref="UsrDto"/>.
    /// </summary>
    public static partial class UsrHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="UsrDto"/> converted from <see cref="Usr"/>.</param>
        static partial void OnDTO(this Usr entity, UsrDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Usr"/> converted from <see cref="UsrDto"/>.</param>
        static partial void OnEntity(this UsrDto dto, Usr entity);

        /// <summary>
        /// Converts this instance of <see cref="UsrDto"/> to an instance of <see cref="Usr"/>.
        /// </summary>
        /// <param name="dto"><see cref="UsrDto"/> to convert.</param>
        public static Usr ToEntity(this UsrDto dto)
        {
            if (dto == null) return null;

            var entity = new Usr();

            entity.Id = dto.Id;
            entity.Username = dto.Username;
            entity.Password = dto.Password;
            entity.Active = dto.Active;
            entity.Description = dto.Description;
            entity.DateValid = dto.DateValid;
            entity.DateRegistration = dto.DateRegistration;
            entity.IdUserType = dto.IdUserType;
            entity.IdPerson = dto.IdPerson;
            entity.ConfirmationCode = dto.ConfirmationCode;
            entity.IdCreated = dto.IdCreated;
            entity.DateCreated = dto.DateCreated;
            entity.IdUpdated = dto.IdUpdated;
            entity.DateUpdated = dto.DateUpdated;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Usr"/> to an instance of <see cref="UsrDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="Usr"/> to convert.</param>
        public static UsrDto ToDTO(this Usr entity)
        {
            if (entity == null) return null;

            var dto = new UsrDto();

            dto.Id = entity.Id;
            dto.Username = entity.Username;
            dto.Password = entity.Password;
            dto.Active = entity.Active;
            dto.Description = entity.Description;
            dto.DateValid = entity.DateValid;
            dto.DateRegistration = entity.DateRegistration;
            dto.IdUserType = entity.IdUserType;
            dto.IdPerson = entity.IdPerson;
            dto.ConfirmationCode = entity.ConfirmationCode;
            dto.IdCreated = entity.IdCreated;
            dto.DateCreated = entity.DateCreated;
            dto.IdUpdated = entity.IdUpdated;
            dto.DateUpdated = entity.DateUpdated;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="UsrDto"/> to an instance of <see cref="Usr"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Usr> ToEntities(this IEnumerable<UsrDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Usr"/> to an instance of <see cref="UsrDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<UsrDto> ToDTOs(this IEnumerable<Usr> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}