//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:56:51
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{
    public partial class CompanyDto
    {
        public int Id { get; set; }

        public string CompanyName { get; set; }

        public int? CompanyType { get; set; }

        public int? IdRegion { get; set; }

        public string Address { get; set; }

        public string City { get; set; }

        public string Country { get; set; }

        public string Email { get; set; }

        public string IdOwnerXX { get; set; }

        public CompanyDto()
        {
        }

        public CompanyDto(int id, string companyName, int? companyType, int? idRegion, string address, string city, string country, string email, string idOwnerXX)
        {
			this.Id = id;
			this.CompanyName = companyName;
			this.CompanyType = companyType;
			this.IdRegion = idRegion;
			this.Address = address;
			this.City = city;
			this.Country = country;
			this.Email = email;
			this.IdOwnerXX = idOwnerXX;
        }
    }
}