//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:57:44
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{
    public partial class DirUsrTypeDto
    {
        public int Id { get; set; }

        public string Code { get; set; }

        public string Name { get; set; }

        public string Text { get; set; }

        public bool Active { get; set; }

        public string Description { get; set; }

        public int IdCreated { get; set; }

        public DateTime DateCreated { get; set; }

        public int? IdUpdated { get; set; }

        public DateTime? DateUpdated { get; set; }

        public int? IdDeleted { get; set; }

        public DateTime? DateDeleted { get; set; }

        public DirUsrTypeDto()
        {
        }

        public DirUsrTypeDto(int id, string code, string name, string text, bool active, string description, int idCreated, DateTime dateCreated, int? idUpdated, DateTime? dateUpdated, int? idDeleted, DateTime? dateDeleted)
        {
			this.Id = id;
			this.Code = code;
			this.Name = name;
			this.Text = text;
			this.Active = active;
			this.Description = description;
			this.IdCreated = idCreated;
			this.DateCreated = dateCreated;
			this.IdUpdated = idUpdated;
			this.DateUpdated = dateUpdated;
			this.IdDeleted = idDeleted;
			this.DateDeleted = dateDeleted;
        }
    }
}