//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.15 - 23:40:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{
    public partial class OfferDto
    {
        public int Id { get; set; }

        public int? IdCompany { get; set; }

        public int? IdShip { get; set; }

        public DateTime Timestamp { get; set; }

        public int? IdReturnPort { get; set; }

        public DateTime? ReturnTime { get; set; }

        public DateTime? HandoverTimeInPort { get; set; }

        public string HandoverLocationOutPort { get; set; }

        public DateTime? HandoverTimeOutPort { get; set; }

        public DateTime? ValidTime { get; set; }

        public int? IdPaymentMethod { get; set; }

        public int IdUser { get; set; }

        public string Note { get; set; }

        public bool? Active { get; set; }

        public int IdCreated { get; set; }

        public DateTime DateCreated { get; set; }

        public int? IdUpdated { get; set; }

        public DateTime? DateUpdated { get; set; }
    }
}