//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.04 - 22:49:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{
    public partial class OfferDto
    {
        public int Id { get; set; }

        public int? IdCompany { get; set; }

        public int? IdShip { get; set; }

        public DateTime Timestamp { get; set; }

        public int? IdReturnPort { get; set; }

        public DateTime? ReturnTime { get; set; }

        public DateTime? HandoverTimeInPort { get; set; }

        public string HandoverLocationOutPort { get; set; }

        public DateTime? HandoverTimeOutPort { get; set; }

        public DateTime? ValidTime { get; set; }

        public int? IdPaymentMethod { get; set; }

        public int IdUser { get; set; }

        public string Note { get; set; }

        public bool? Active { get; set; }

        public int IdCreated { get; set; }

        public DateTime DateCreated { get; set; }

        public int? IdUpdated { get; set; }

        public DateTime? DateUpdated { get; set; }

        public OfferDto()
        {
        }

        public OfferDto(int id, int? idCompany, int? idShip, DateTime timestamp, int? idReturnPort, DateTime? returnTime, DateTime? handoverTimeInPort, string handoverLocationOutPort, DateTime? handoverTimeOutPort, DateTime? validTime, int? idPaymentMethod, int idUser, string note, bool? active, int idCreated, DateTime dateCreated, int? idUpdated, DateTime? dateUpdated)
        {
			this.Id = id;
			this.IdCompany = idCompany;
			this.IdShip = idShip;
			this.Timestamp = timestamp;
			this.IdReturnPort = idReturnPort;
			this.ReturnTime = returnTime;
			this.HandoverTimeInPort = handoverTimeInPort;
			this.HandoverLocationOutPort = handoverLocationOutPort;
			this.HandoverTimeOutPort = handoverTimeOutPort;
			this.ValidTime = validTime;
			this.IdPaymentMethod = idPaymentMethod;
			this.IdUser = idUser;
			this.Note = note;
			this.Active = active;
			this.IdCreated = idCreated;
			this.DateCreated = dateCreated;
			this.IdUpdated = idUpdated;
			this.DateUpdated = dateUpdated;
        }
    }
}