//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:57:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{
    public partial class OfferItemDto
    {
        public int Id { get; set; }

        public int IdOffer { get; set; }

        public int? IdZone { get; set; }

        public int IdFish { get; set; }

        public int? IdFishCategory { get; set; }

        public bool? IsFarmed { get; set; }

        public double? Qty { get; set; }

        public double? UnitPrice { get; set; }

        public string ProductImage { get; set; }

        public byte[] ProductImageBin { get; set; }

        public string Note { get; set; }

        public int? IdFishCondition { get; set; }

        public DateTime? CatchTime { get; set; }

        public DateTime? FreezeTime { get; set; }

        public int IdCreated { get; set; }

        public DateTime DateCreated { get; set; }

        public int? IdUpdated { get; set; }

        public DateTime? DateUpdated { get; set; }

        public int Offer_Id { get; set; }

        public OfferItemDto()
        {
        }

        public OfferItemDto(int id, int idOffer, int? idZone, int idFish, int? idFishCategory, bool? isFarmed, double? qty, double? unitPrice, string productImage, byte[] productImageBin, string note, int? idFishCondition, DateTime? catchTime, DateTime? freezeTime, int idCreated, DateTime dateCreated, int? idUpdated, DateTime? dateUpdated, int offer_Id)
        {
			this.Id = id;
			this.IdOffer = idOffer;
			this.IdZone = idZone;
			this.IdFish = idFish;
			this.IdFishCategory = idFishCategory;
			this.IsFarmed = isFarmed;
			this.Qty = qty;
			this.UnitPrice = unitPrice;
			this.ProductImage = productImage;
			this.ProductImageBin = productImageBin;
			this.Note = note;
			this.IdFishCondition = idFishCondition;
			this.CatchTime = catchTime;
			this.FreezeTime = freezeTime;
			this.IdCreated = idCreated;
			this.DateCreated = dateCreated;
			this.IdUpdated = idUpdated;
			this.DateUpdated = dateUpdated;
			this.Offer_Id = offer_Id;
        }
    }
}