//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:58:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{
    public partial class PrsDto
    {
        public int Id { get; set; }

        public string Firstname { get; set; }

        public string Lastname { get; set; }

        public bool Active { get; set; }

        public string Email { get; set; }

        public bool? EmailVerified { get; set; }

        public int? IdCompany { get; set; }

        public string Address { get; set; }

        public string City { get; set; }

        public string Country { get; set; }

        public string Phone { get; set; }

        public string Mobile { get; set; }

        public int IdCreated { get; set; }

        public DateTime DateCreated { get; set; }

        public int? IdUpdated { get; set; }

        public DateTime? DateUpdated { get; set; }

        public int? IdShip { get; set; }

        public PrsDto()
        {
        }

        public PrsDto(int id, string firstname, string lastname, bool active, string email, bool? emailVerified, int? idCompany, string address, string city, string country, string phone, string mobile, int idCreated, DateTime dateCreated, int? idUpdated, DateTime? dateUpdated, int? idShip)
        {
			this.Id = id;
			this.Firstname = firstname;
			this.Lastname = lastname;
			this.Active = active;
			this.Email = email;
			this.EmailVerified = emailVerified;
			this.IdCompany = idCompany;
			this.Address = address;
			this.City = city;
			this.Country = country;
			this.Phone = phone;
			this.Mobile = mobile;
			this.IdCreated = idCreated;
			this.DateCreated = dateCreated;
			this.IdUpdated = idUpdated;
			this.DateUpdated = dateUpdated;
			this.IdShip = idShip;
        }
    }
}