//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:59:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{
    public partial class ShipDto
    {
        public int Id { get; set; }

        public string ShipName { get; set; }

        public string ShipRegistration { get; set; }

        public double? LengthFloat { get; set; }

        public float? LengthReal { get; set; }

        public int? IdShipType { get; set; }

        public float? Capacity { get; set; }

        public int? IdCompany { get; set; }

        public int? IdCaptain { get; set; }

        public int? IdBasePort { get; set; }

        public int? IdUnloadPort { get; set; }

        public bool? Active { get; set; }

        public int IdCreated { get; set; }

        public DateTime DateCreated { get; set; }

        public int? IdUpdated { get; set; }

        public DateTime? DateUpdated { get; set; }

        public ShipDto()
        {
        }

        public ShipDto(int id, string shipName, string shipRegistration, double? lengthFloat, float? lengthReal, int? idShipType, float? capacity, int? idCompany, int? idCaptain, int? idBasePort, int? idUnloadPort, bool? active, int idCreated, DateTime dateCreated, int? idUpdated, DateTime? dateUpdated)
        {
			this.Id = id;
			this.ShipName = shipName;
			this.ShipRegistration = shipRegistration;
			this.LengthFloat = lengthFloat;
			this.LengthReal = lengthReal;
			this.IdShipType = idShipType;
			this.Capacity = capacity;
			this.IdCompany = idCompany;
			this.IdCaptain = idCaptain;
			this.IdBasePort = idBasePort;
			this.IdUnloadPort = idUnloadPort;
			this.Active = active;
			this.IdCreated = idCreated;
			this.DateCreated = dateCreated;
			this.IdUpdated = idUpdated;
			this.DateUpdated = dateUpdated;
        }
    }
}