//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017.04.03 - 18:59:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Collections.Generic;
using System;

namespace DTO
{
    public partial class UsrDto
    {
        public int Id { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public bool Active { get; set; }

        public string Description { get; set; }

        public DateTime? DateValid { get; set; }

        public DateTime? DateRegistration { get; set; }

        public int? IdUserType { get; set; }

        public int? IdPerson { get; set; }

        public string ConfirmationCode { get; set; }

        public int IdCreated { get; set; }

        public DateTime DateCreated { get; set; }

        public int? IdUpdated { get; set; }

        public DateTime? DateUpdated { get; set; }

        public UsrDto()
        {
        }

        public UsrDto(int id, string username, string password, bool active, string description, DateTime? dateValid, DateTime? dateRegistration, int? idUserType, int? idPerson, string confirmationCode, int idCreated, DateTime dateCreated, int? idUpdated, DateTime? dateUpdated)
        {
			this.Id = id;
			this.Username = username;
			this.Password = password;
			this.Active = active;
			this.Description = description;
			this.DateValid = dateValid;
			this.DateRegistration = dateRegistration;
			this.IdUserType = idUserType;
			this.IdPerson = idPerson;
			this.ConfirmationCode = confirmationCode;
			this.IdCreated = idCreated;
			this.DateCreated = dateCreated;
			this.IdUpdated = idUpdated;
			this.DateUpdated = dateUpdated;
        }
    }
}